Added usage notes for the `CLI`
zeskeertwee/vach pull request #48
Opened 2021-12-12 16:55 UTC by sokorototo

Other changes include:
 - Better `Leaf::template` function
 - `cargo fmt`
 - Updates to the docs

2021-12-18 10:59 UTC, zeskeertwee requested changes

2021-12-18 10:59 UTC, zeskeertwee commented on vach-cli/src/commands/unpack.rs
> +			#[allow(unused_must_use)] { fs::create_dir_all(parent_dir); }
Why don't we check the return value?

2021-12-19 12:40 UTC, sokorototo commented on vach-cli/src/commands/unpack.rs
> +			#[allow(unused_must_use)] { fs::create_dir_all(parent_dir); }
It's not the same in the current commit

2021-12-20 22:03 UTC, zeskeertwee commented on vach-cli/src/commands/unpack.rs
> +			#[allow(unused_must_use)] { fs::create_dir_all(parent_dir); }
What do you mean?

2021-12-24 12:41 UTC, zeskeertwee approved these changes

2021-12-24 12:41 UTC, merged